### PR TITLE
3.2 - README Update

### PR DESCRIPTION
**Pull request by cheeseng**
Updated README for 3.2.0.0.

Note: This is staged as 3.2.0.0 release.

### CODE REVIEW

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by bvenners** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Pull request merged**
